application: engineapp-1058
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

# Serve stylesheets.
- url: /stylesheets
  static_dir: stylesheets

- url: /infinity
  script: /infinity/index.php

- url: /chat
  script: /chat/index.php

- url: /admin
  script: /admin/index.php

- url: /definition
  script: /definition/index.php

- url: /
  script: index.php

- url: /.*
  script: 404.php
